#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 28

enum {
  sym_ident = 1,
  sym__lparen = 2,
  sym__rparen = 3,
  sym__lbrack = 4,
  sym__rbrack = 5,
  sym__lbrace = 6,
  sym__rbrace = 7,
  sym__comma = 8,
  sym__period = 9,
  sym__eq = 10,
  sym__colon = 11,
  sym__arrow = 12,
  sym__pound = 13,
  sym__poundPound = 14,
  sym__newline = 15,
  aux_sym__comment_token1 = 16,
  anon_sym_type = 17,
  anon_sym_async = 18,
  anon_sym_const = 19,
  anon_sym_export = 20,
  anon_sym_builtin = 21,
  anon_sym_func = 22,
  sym_klass = 23,
  sym_source_file = 24,
  sym__comment = 25,
  sym_docComment = 26,
  sym__typeArgs = 27,
  sym_typeExpr = 28,
  sym_typeName = 29,
  sym_typeDecl = 30,
  sym__innerOrAlias = 31,
  sym__typeInner = 32,
  sym_typeVariant = 33,
  sym_typeAnnotated = 34,
  sym_funcHead = 35,
  sym_func = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym__typeArgs_repeat1 = 38,
  aux_sym_typeName_repeat1 = 39,
  aux_sym__typeInner_repeat1 = 40,
  aux_sym__typeInner_repeat2 = 41,
  aux_sym__typeInner_repeat3 = 42,
  aux_sym_funcHead_repeat1 = 43,
  aux_sym_funcHead_repeat2 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [sym__lparen] = "_lparen",
  [sym__rparen] = "_rparen",
  [sym__lbrack] = "_lbrack",
  [sym__rbrack] = "_rbrack",
  [sym__lbrace] = "_lbrace",
  [sym__rbrace] = "_rbrace",
  [sym__comma] = "_comma",
  [sym__period] = "_period",
  [sym__eq] = "_eq",
  [sym__colon] = "_colon",
  [sym__arrow] = "_arrow",
  [sym__pound] = "_pound",
  [sym__poundPound] = "_poundPound",
  [sym__newline] = "_newline",
  [aux_sym__comment_token1] = "_comment_token1",
  [anon_sym_type] = "type",
  [anon_sym_async] = "async",
  [anon_sym_const] = "const",
  [anon_sym_export] = "export",
  [anon_sym_builtin] = "builtin",
  [anon_sym_func] = "func",
  [sym_klass] = "klass",
  [sym_source_file] = "source_file",
  [sym__comment] = "_comment",
  [sym_docComment] = "docComment",
  [sym__typeArgs] = "_typeArgs",
  [sym_typeExpr] = "typeExpr",
  [sym_typeName] = "typeName",
  [sym_typeDecl] = "typeDecl",
  [sym__innerOrAlias] = "_innerOrAlias",
  [sym__typeInner] = "_typeInner",
  [sym_typeVariant] = "typeVariant",
  [sym_typeAnnotated] = "typeAnnotated",
  [sym_funcHead] = "funcHead",
  [sym_func] = "func",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__typeArgs_repeat1] = "_typeArgs_repeat1",
  [aux_sym_typeName_repeat1] = "typeName_repeat1",
  [aux_sym__typeInner_repeat1] = "_typeInner_repeat1",
  [aux_sym__typeInner_repeat2] = "_typeInner_repeat2",
  [aux_sym__typeInner_repeat3] = "_typeInner_repeat3",
  [aux_sym_funcHead_repeat1] = "funcHead_repeat1",
  [aux_sym_funcHead_repeat2] = "funcHead_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [sym__lparen] = sym__lparen,
  [sym__rparen] = sym__rparen,
  [sym__lbrack] = sym__lbrack,
  [sym__rbrack] = sym__rbrack,
  [sym__lbrace] = sym__lbrace,
  [sym__rbrace] = sym__rbrace,
  [sym__comma] = sym__comma,
  [sym__period] = sym__period,
  [sym__eq] = sym__eq,
  [sym__colon] = sym__colon,
  [sym__arrow] = sym__arrow,
  [sym__pound] = sym__pound,
  [sym__poundPound] = sym__poundPound,
  [sym__newline] = sym__newline,
  [aux_sym__comment_token1] = aux_sym__comment_token1,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_async] = anon_sym_async,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_builtin] = anon_sym_builtin,
  [anon_sym_func] = anon_sym_func,
  [sym_klass] = sym_klass,
  [sym_source_file] = sym_source_file,
  [sym__comment] = sym__comment,
  [sym_docComment] = sym_docComment,
  [sym__typeArgs] = sym__typeArgs,
  [sym_typeExpr] = sym_typeExpr,
  [sym_typeName] = sym_typeName,
  [sym_typeDecl] = sym_typeDecl,
  [sym__innerOrAlias] = sym__innerOrAlias,
  [sym__typeInner] = sym__typeInner,
  [sym_typeVariant] = sym_typeVariant,
  [sym_typeAnnotated] = sym_typeAnnotated,
  [sym_funcHead] = sym_funcHead,
  [sym_func] = sym_func,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__typeArgs_repeat1] = aux_sym__typeArgs_repeat1,
  [aux_sym_typeName_repeat1] = aux_sym_typeName_repeat1,
  [aux_sym__typeInner_repeat1] = aux_sym__typeInner_repeat1,
  [aux_sym__typeInner_repeat2] = aux_sym__typeInner_repeat2,
  [aux_sym__typeInner_repeat3] = aux_sym__typeInner_repeat3,
  [aux_sym_funcHead_repeat1] = aux_sym_funcHead_repeat1,
  [aux_sym_funcHead_repeat2] = aux_sym_funcHead_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym__lparen] = {
    .visible = false,
    .named = true,
  },
  [sym__rparen] = {
    .visible = false,
    .named = true,
  },
  [sym__lbrack] = {
    .visible = false,
    .named = true,
  },
  [sym__rbrack] = {
    .visible = false,
    .named = true,
  },
  [sym__lbrace] = {
    .visible = false,
    .named = true,
  },
  [sym__rbrace] = {
    .visible = false,
    .named = true,
  },
  [sym__comma] = {
    .visible = false,
    .named = true,
  },
  [sym__period] = {
    .visible = false,
    .named = true,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [sym__colon] = {
    .visible = false,
    .named = true,
  },
  [sym__arrow] = {
    .visible = false,
    .named = true,
  },
  [sym__pound] = {
    .visible = false,
    .named = true,
  },
  [sym__poundPound] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_async] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_builtin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [sym_klass] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_docComment] = {
    .visible = true,
    .named = true,
  },
  [sym__typeArgs] = {
    .visible = false,
    .named = true,
  },
  [sym_typeExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_typeName] = {
    .visible = true,
    .named = true,
  },
  [sym_typeDecl] = {
    .visible = true,
    .named = true,
  },
  [sym__innerOrAlias] = {
    .visible = false,
    .named = true,
  },
  [sym__typeInner] = {
    .visible = false,
    .named = true,
  },
  [sym_typeVariant] = {
    .visible = true,
    .named = true,
  },
  [sym_typeAnnotated] = {
    .visible = true,
    .named = true,
  },
  [sym_funcHead] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeArgs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeName_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_args = 2,
  field_body = 3,
  field_instantiate = 4,
  field_method = 5,
  field_name = 6,
  field_property = 7,
  field_return = 8,
  field_type = 9,
  field_variant = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_args] = "args",
  [field_body] = "body",
  [field_instantiate] = "instantiate",
  [field_method] = "method",
  [field_name] = "name",
  [field_property] = "property",
  [field_return] = "return",
  [field_type] = "type",
  [field_variant] = "variant",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 5},
  [3] = {.index = 6, .length = 3},
  [4] = {.index = 9, .length = 2},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 2},
  [7] = {.index = 14, .length = 5},
  [8] = {.index = 19, .length = 1},
  [9] = {.index = 20, .length = 1},
  [10] = {.index = 21, .length = 1},
  [11] = {.index = 22, .length = 2},
  [12] = {.index = 24, .length = 1},
  [13] = {.index = 25, .length = 2},
  [14] = {.index = 27, .length = 2},
  [15] = {.index = 29, .length = 2},
  [16] = {.index = 31, .length = 2},
  [17] = {.index = 33, .length = 3},
  [18] = {.index = 36, .length = 3},
  [19] = {.index = 39, .length = 2},
  [20] = {.index = 41, .length = 3},
  [21] = {.index = 44, .length = 4},
  [22] = {.index = 48, .length = 4},
  [23] = {.index = 52, .length = 3},
  [24] = {.index = 55, .length = 3},
  [25] = {.index = 58, .length = 5},
  [26] = {.index = 63, .length = 4},
  [27] = {.index = 67, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_alias, 2, .inherited = true},
    {field_method, 2, .inherited = true},
    {field_name, 1},
    {field_property, 2, .inherited = true},
    {field_variant, 2, .inherited = true},
  [6] =
    {field_method, 0, .inherited = true},
    {field_property, 0, .inherited = true},
    {field_variant, 0, .inherited = true},
  [9] =
    {field_body, 1},
    {field_body, 2},
  [11] =
    {field_name, 0},
  [12] =
    {field_alias, 0},
    {field_alias, 1},
  [14] =
    {field_alias, 1, .inherited = true},
    {field_method, 1, .inherited = true},
    {field_name, 0},
    {field_property, 1, .inherited = true},
    {field_variant, 1, .inherited = true},
  [19] =
    {field_property, 1},
  [20] =
    {field_variant, 1},
  [21] =
    {field_method, 1},
  [22] =
    {field_args, 3},
    {field_name, 1},
  [24] =
    {field_name, 2},
  [25] =
    {field_name, 0},
    {field_type, 2},
  [27] =
    {field_property, 1},
    {field_variant, 2},
  [29] =
    {field_method, 2},
    {field_property, 1},
  [31] =
    {field_method, 2},
    {field_variant, 1},
  [33] =
    {field_name, 1},
    {field_return, 4},
    {field_return, 5},
  [36] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
  [39] =
    {field_args, 4},
    {field_name, 2},
  [41] =
    {field_method, 3},
    {field_property, 1},
    {field_variant, 2},
  [44] =
    {field_instantiate, 1},
    {field_instantiate, 2},
    {field_instantiate, 3},
    {field_name, 0},
  [48] =
    {field_args, 3},
    {field_name, 1},
    {field_return, 5},
    {field_return, 6},
  [52] =
    {field_name, 2},
    {field_return, 5},
    {field_return, 6},
  [55] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
  [58] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
    {field_return, 6},
    {field_return, 7},
  [63] =
    {field_args, 4},
    {field_name, 2},
    {field_return, 6},
    {field_return, 7},
  [67] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
    {field_return, 7},
    {field_return, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == ',') ADVANCE(10);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead == '[') ADVANCE(6);
      if (lookahead == ']') ADVANCE(7);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym__lparen);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__rparen);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__lbrack);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__rbrack);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__lbrace);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym__rbrace);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__comma);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__period);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__eq);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__colon);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__arrow);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__pound);
      if (lookahead == '#') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__pound);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__poundPound);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__poundPound);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_async);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_klass);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_builtin);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 20},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 20},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {(TSStateId)(-1)},
  [96] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym__comment] = STATE(0),
    [sym_docComment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym__lparen] = ACTIONS(1),
    [sym__rparen] = ACTIONS(1),
    [sym__lbrack] = ACTIONS(1),
    [sym__rbrack] = ACTIONS(1),
    [sym__lbrace] = ACTIONS(1),
    [sym__rbrace] = ACTIONS(1),
    [sym__comma] = ACTIONS(1),
    [sym__period] = ACTIONS(1),
    [sym__eq] = ACTIONS(1),
    [sym__colon] = ACTIONS(1),
    [sym__arrow] = ACTIONS(1),
    [sym__pound] = ACTIONS(3),
    [sym__poundPound] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_async] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_builtin] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [sym_klass] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym__comment] = STATE(1),
    [sym_docComment] = STATE(1),
    [sym_typeDecl] = STATE(37),
    [sym_funcHead] = STATE(74),
    [sym_func] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_funcHead_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym__pound] = ACTIONS(3),
    [sym__poundPound] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_async] = ACTIONS(11),
    [anon_sym_const] = ACTIONS(11),
    [anon_sym_export] = ACTIONS(11),
    [anon_sym_builtin] = ACTIONS(11),
    [anon_sym_func] = ACTIONS(13),
    [sym_klass] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(21), 1,
      sym__period,
    STATE(2), 3,
      sym__comment,
      sym_docComment,
      aux_sym_typeName_repeat1,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(19), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [34] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(4), 1,
      aux_sym_typeName_repeat1,
    STATE(3), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(24), 7,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(26), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [70] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(2), 1,
      aux_sym_typeName_repeat1,
    STATE(4), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(30), 7,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(32), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [106] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(5), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(17), 8,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
      sym__period,
    ACTIONS(19), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [137] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(38), 1,
      sym__lbrack,
    STATE(6), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(34), 6,
      ts_builtin_sym_end,
      sym__rparen,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(36), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [169] = 15,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(40), 1,
      sym_ident,
    ACTIONS(42), 1,
      sym__rbrace,
    ACTIONS(46), 1,
      anon_sym_func,
    STATE(13), 1,
      aux_sym__typeInner_repeat2,
    STATE(21), 1,
      aux_sym__typeInner_repeat3,
    STATE(34), 1,
      aux_sym__typeInner_repeat1,
    STATE(38), 1,
      sym_typeAnnotated,
    STATE(39), 1,
      sym_typeVariant,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(7), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [219] = 15,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(40), 1,
      sym_ident,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(48), 1,
      sym__rbrace,
    STATE(7), 1,
      aux_sym__typeInner_repeat1,
    STATE(12), 1,
      aux_sym__typeInner_repeat2,
    STATE(18), 1,
      aux_sym__typeInner_repeat3,
    STATE(38), 1,
      sym_typeAnnotated,
    STATE(39), 1,
      sym_typeVariant,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(8), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [269] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(9), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(50), 6,
      ts_builtin_sym_end,
      sym__rparen,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(52), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [298] = 11,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      anon_sym_type,
    ACTIONS(62), 1,
      anon_sym_func,
    ACTIONS(65), 1,
      sym_klass,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(37), 2,
      sym_typeDecl,
      sym_func,
    STATE(10), 3,
      sym__comment,
      sym_docComment,
      aux_sym_source_file_repeat1,
    ACTIONS(59), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [338] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(13), 1,
      anon_sym_func,
    ACTIONS(15), 1,
      sym_klass,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(11), 2,
      sym__comment,
      sym_docComment,
    STATE(37), 2,
      sym_typeDecl,
      sym_func,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [380] = 13,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(70), 1,
      sym_ident,
    ACTIONS(72), 1,
      sym__rbrace,
    STATE(22), 1,
      aux_sym__typeInner_repeat3,
    STATE(32), 1,
      aux_sym__typeInner_repeat2,
    STATE(39), 1,
      sym_typeVariant,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(12), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [424] = 13,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(70), 1,
      sym_ident,
    ACTIONS(74), 1,
      sym__rbrace,
    STATE(17), 1,
      aux_sym__typeInner_repeat3,
    STATE(32), 1,
      aux_sym__typeInner_repeat2,
    STATE(39), 1,
      sym_typeVariant,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(13), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [468] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(78), 1,
      sym__lbrace,
    ACTIONS(80), 1,
      sym__rbrace,
    ACTIONS(82), 1,
      sym__eq,
    ACTIONS(84), 1,
      sym__colon,
    STATE(25), 1,
      sym__typeInner,
    STATE(40), 1,
      sym__innerOrAlias,
    STATE(14), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(76), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [505] = 8,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(78), 1,
      sym__lbrace,
    ACTIONS(82), 1,
      sym__eq,
    STATE(25), 1,
      sym__typeInner,
    STATE(36), 1,
      sym__innerOrAlias,
    STATE(15), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [538] = 9,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(78), 1,
      sym__lbrace,
    ACTIONS(80), 1,
      sym__rbrace,
    ACTIONS(82), 1,
      sym__eq,
    STATE(25), 1,
      sym__typeInner,
    STATE(40), 1,
      sym__innerOrAlias,
    STATE(16), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(76), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [572] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      anon_sym_func,
    ACTIONS(88), 1,
      sym__rbrace,
    STATE(24), 1,
      aux_sym__typeInner_repeat3,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(17), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [607] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      anon_sym_func,
    ACTIONS(90), 1,
      sym__rbrace,
    STATE(24), 1,
      aux_sym__typeInner_repeat3,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(18), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [642] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(19), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(94), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [667] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(20), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(98), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [692] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      anon_sym_func,
    ACTIONS(100), 1,
      sym__rbrace,
    STATE(24), 1,
      aux_sym__typeInner_repeat3,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(21), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [727] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      anon_sym_func,
    ACTIONS(102), 1,
      sym__rbrace,
    STATE(24), 1,
      aux_sym__typeInner_repeat3,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(22), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [762] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(23), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(106), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [787] = 9,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(108), 1,
      sym__rbrace,
    ACTIONS(113), 1,
      anon_sym_func,
    STATE(42), 1,
      sym_func,
    STATE(43), 1,
      aux_sym_funcHead_repeat1,
    STATE(74), 1,
      sym_funcHead,
    STATE(24), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat3,
    ACTIONS(110), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [820] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(25), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(118), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [845] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(26), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(122), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [870] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(27), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(126), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [895] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(28), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(130), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [920] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(29), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(134), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [945] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(30), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(138), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [970] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(31), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(142), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [995] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(144), 1,
      sym_ident,
    ACTIONS(147), 1,
      sym__rbrace,
    STATE(39), 1,
      sym_typeVariant,
    STATE(32), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat2,
    ACTIONS(149), 5,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [1023] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(33), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      sym__rbrace,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [1045] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(153), 1,
      sym_ident,
    ACTIONS(156), 1,
      sym__rbrace,
    STATE(38), 1,
      sym_typeAnnotated,
    STATE(34), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat1,
    ACTIONS(158), 5,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [1073] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(35), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(162), 3,
      sym__rparen,
      sym__rbrace,
      sym__comma,
    ACTIONS(160), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [1097] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(36), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(164), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [1118] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(37), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(166), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [1139] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(170), 1,
      sym__rbrace,
    STATE(38), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(168), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [1161] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(174), 1,
      sym__rbrace,
    STATE(39), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(172), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [1183] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(178), 1,
      sym__rbrace,
    STATE(40), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(176), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [1205] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(183), 1,
      anon_sym_func,
    STATE(41), 3,
      sym__comment,
      sym_docComment,
      aux_sym_funcHead_repeat1,
    ACTIONS(180), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [1226] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(42), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(185), 6,
      sym__rbrace,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [1245] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(187), 1,
      anon_sym_func,
    STATE(41), 1,
      aux_sym_funcHead_repeat1,
    STATE(43), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [1268] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(44), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(189), 5,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [1286] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(51), 1,
      sym_typeExpr,
    STATE(76), 1,
      sym__typeArgs,
    STATE(45), 2,
      sym__comment,
      sym_docComment,
  [1309] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(71), 1,
      sym_typeExpr,
    STATE(46), 2,
      sym__comment,
      sym_docComment,
  [1329] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(78), 1,
      sym_typeExpr,
    STATE(47), 2,
      sym__comment,
      sym_docComment,
  [1349] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(86), 1,
      sym_typeExpr,
    STATE(48), 2,
      sym__comment,
      sym_docComment,
  [1369] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(193), 1,
      sym_ident,
    ACTIONS(195), 1,
      sym__rparen,
    STATE(58), 1,
      sym_typeAnnotated,
    STATE(49), 2,
      sym__comment,
      sym_docComment,
  [1389] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(30), 1,
      sym_typeExpr,
    STATE(50), 2,
      sym__comment,
      sym_docComment,
  [1409] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(197), 1,
      sym__rbrack,
    ACTIONS(199), 1,
      sym__comma,
    STATE(54), 1,
      aux_sym__typeArgs_repeat1,
    STATE(51), 2,
      sym__comment,
      sym_docComment,
  [1429] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(94), 1,
      sym_typeExpr,
    STATE(52), 2,
      sym__comment,
      sym_docComment,
  [1449] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(93), 1,
      sym_typeExpr,
    STATE(53), 2,
      sym__comment,
      sym_docComment,
  [1469] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(199), 1,
      sym__comma,
    ACTIONS(201), 1,
      sym__rbrack,
    STATE(59), 1,
      aux_sym__typeArgs_repeat1,
    STATE(54), 2,
      sym__comment,
      sym_docComment,
  [1489] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(203), 1,
      sym__rparen,
    ACTIONS(205), 1,
      sym__comma,
    STATE(55), 3,
      sym__comment,
      sym_docComment,
      aux_sym_funcHead_repeat2,
  [1507] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(208), 1,
      sym__rparen,
    ACTIONS(210), 1,
      sym__comma,
    STATE(55), 1,
      aux_sym_funcHead_repeat2,
    STATE(56), 2,
      sym__comment,
      sym_docComment,
  [1527] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(90), 1,
      sym_typeExpr,
    STATE(57), 2,
      sym__comment,
      sym_docComment,
  [1547] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(210), 1,
      sym__comma,
    ACTIONS(212), 1,
      sym__rparen,
    STATE(62), 1,
      aux_sym_funcHead_repeat2,
    STATE(58), 2,
      sym__comment,
      sym_docComment,
  [1567] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(214), 1,
      sym__rbrack,
    ACTIONS(216), 1,
      sym__comma,
    STATE(59), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeArgs_repeat1,
  [1585] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(193), 1,
      sym_ident,
    ACTIONS(219), 1,
      sym__rparen,
    STATE(64), 1,
      sym_typeAnnotated,
    STATE(60), 2,
      sym__comment,
      sym_docComment,
  [1605] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(35), 1,
      sym_typeExpr,
    STATE(61), 2,
      sym__comment,
      sym_docComment,
  [1625] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(210), 1,
      sym__comma,
    ACTIONS(221), 1,
      sym__rparen,
    STATE(55), 1,
      aux_sym_funcHead_repeat2,
    STATE(62), 2,
      sym__comment,
      sym_docComment,
  [1645] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(191), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(88), 1,
      sym_typeExpr,
    STATE(63), 2,
      sym__comment,
      sym_docComment,
  [1665] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(210), 1,
      sym__comma,
    ACTIONS(223), 1,
      sym__rparen,
    STATE(56), 1,
      aux_sym_funcHead_repeat2,
    STATE(64), 2,
      sym__comment,
      sym_docComment,
  [1685] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(225), 1,
      sym__lbrace,
    ACTIONS(227), 1,
      sym__arrow,
    STATE(65), 2,
      sym__comment,
      sym_docComment,
  [1702] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(193), 1,
      sym_ident,
    STATE(72), 1,
      sym_typeAnnotated,
    STATE(66), 2,
      sym__comment,
      sym_docComment,
  [1719] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(229), 1,
      sym__lbrace,
    ACTIONS(231), 1,
      sym__arrow,
    STATE(67), 2,
      sym__comment,
      sym_docComment,
  [1736] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(233), 1,
      sym__lbrace,
    ACTIONS(235), 1,
      sym__arrow,
    STATE(68), 2,
      sym__comment,
      sym_docComment,
  [1753] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(237), 1,
      sym__lbrace,
    ACTIONS(239), 1,
      sym__arrow,
    STATE(69), 2,
      sym__comment,
      sym_docComment,
  [1770] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(241), 1,
      sym__lbrace,
    ACTIONS(243), 1,
      sym__arrow,
    STATE(70), 2,
      sym__comment,
      sym_docComment,
  [1787] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(214), 2,
      sym__rbrack,
      sym__comma,
    STATE(71), 2,
      sym__comment,
      sym_docComment,
  [1802] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(203), 2,
      sym__rparen,
      sym__comma,
    STATE(72), 2,
      sym__comment,
      sym_docComment,
  [1817] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(245), 1,
      sym__lbrace,
    ACTIONS(247), 1,
      sym__arrow,
    STATE(73), 2,
      sym__comment,
      sym_docComment,
  [1834] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(249), 1,
      sym__lbrace,
    STATE(74), 2,
      sym__comment,
      sym_docComment,
  [1848] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(251), 1,
      sym__lparen,
    STATE(75), 2,
      sym__comment,
      sym_docComment,
  [1862] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(253), 1,
      sym__rbrack,
    STATE(76), 2,
      sym__comment,
      sym_docComment,
  [1876] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(255), 1,
      sym_ident,
    STATE(77), 2,
      sym__comment,
      sym_docComment,
  [1890] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(257), 1,
      sym__lbrace,
    STATE(78), 2,
      sym__comment,
      sym_docComment,
  [1904] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(84), 1,
      sym__colon,
    STATE(79), 2,
      sym__comment,
      sym_docComment,
  [1918] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(259), 1,
      sym__poundPound,
    ACTIONS(261), 1,
      sym__newline,
    STATE(80), 2,
      sym__comment,
      sym_docComment,
  [1932] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(259), 1,
      sym__poundPound,
    ACTIONS(263), 1,
      sym__newline,
    STATE(81), 2,
      sym__comment,
      sym_docComment,
  [1946] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(265), 1,
      sym_ident,
    STATE(82), 2,
      sym__comment,
      sym_docComment,
  [1960] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(259), 1,
      sym__poundPound,
    ACTIONS(267), 1,
      aux_sym__comment_token1,
    STATE(83), 2,
      sym__comment,
      sym_docComment,
  [1974] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(269), 1,
      sym_ident,
    STATE(84), 2,
      sym__comment,
      sym_docComment,
  [1988] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    STATE(85), 2,
      sym__comment,
      sym_docComment,
  [2002] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(273), 1,
      sym__lbrace,
    STATE(86), 2,
      sym__comment,
      sym_docComment,
  [2016] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(275), 1,
      sym__rbrace,
    STATE(87), 2,
      sym__comment,
      sym_docComment,
  [2030] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(277), 1,
      sym__lbrace,
    STATE(88), 2,
      sym__comment,
      sym_docComment,
  [2044] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(279), 1,
      sym_ident,
    STATE(89), 2,
      sym__comment,
      sym_docComment,
  [2058] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(281), 1,
      sym__lbrace,
    STATE(90), 2,
      sym__comment,
      sym_docComment,
  [2072] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(259), 1,
      sym__poundPound,
    ACTIONS(283), 1,
      aux_sym__comment_token1,
    STATE(91), 2,
      sym__comment,
      sym_docComment,
  [2086] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(285), 1,
      sym__lparen,
    STATE(92), 2,
      sym__comment,
      sym_docComment,
  [2100] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(287), 1,
      sym__lbrace,
    STATE(93), 2,
      sym__comment,
      sym_docComment,
  [2114] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(289), 1,
      sym__lbrace,
    STATE(94), 2,
      sym__comment,
      sym_docComment,
  [2128] = 1,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
  [2132] = 1,
    ACTIONS(293), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 106,
  [SMALL_STATE(6)] = 137,
  [SMALL_STATE(7)] = 169,
  [SMALL_STATE(8)] = 219,
  [SMALL_STATE(9)] = 269,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 338,
  [SMALL_STATE(12)] = 380,
  [SMALL_STATE(13)] = 424,
  [SMALL_STATE(14)] = 468,
  [SMALL_STATE(15)] = 505,
  [SMALL_STATE(16)] = 538,
  [SMALL_STATE(17)] = 572,
  [SMALL_STATE(18)] = 607,
  [SMALL_STATE(19)] = 642,
  [SMALL_STATE(20)] = 667,
  [SMALL_STATE(21)] = 692,
  [SMALL_STATE(22)] = 727,
  [SMALL_STATE(23)] = 762,
  [SMALL_STATE(24)] = 787,
  [SMALL_STATE(25)] = 820,
  [SMALL_STATE(26)] = 845,
  [SMALL_STATE(27)] = 870,
  [SMALL_STATE(28)] = 895,
  [SMALL_STATE(29)] = 920,
  [SMALL_STATE(30)] = 945,
  [SMALL_STATE(31)] = 970,
  [SMALL_STATE(32)] = 995,
  [SMALL_STATE(33)] = 1023,
  [SMALL_STATE(34)] = 1045,
  [SMALL_STATE(35)] = 1073,
  [SMALL_STATE(36)] = 1097,
  [SMALL_STATE(37)] = 1118,
  [SMALL_STATE(38)] = 1139,
  [SMALL_STATE(39)] = 1161,
  [SMALL_STATE(40)] = 1183,
  [SMALL_STATE(41)] = 1205,
  [SMALL_STATE(42)] = 1226,
  [SMALL_STATE(43)] = 1245,
  [SMALL_STATE(44)] = 1268,
  [SMALL_STATE(45)] = 1286,
  [SMALL_STATE(46)] = 1309,
  [SMALL_STATE(47)] = 1329,
  [SMALL_STATE(48)] = 1349,
  [SMALL_STATE(49)] = 1369,
  [SMALL_STATE(50)] = 1389,
  [SMALL_STATE(51)] = 1409,
  [SMALL_STATE(52)] = 1429,
  [SMALL_STATE(53)] = 1449,
  [SMALL_STATE(54)] = 1469,
  [SMALL_STATE(55)] = 1489,
  [SMALL_STATE(56)] = 1507,
  [SMALL_STATE(57)] = 1527,
  [SMALL_STATE(58)] = 1547,
  [SMALL_STATE(59)] = 1567,
  [SMALL_STATE(60)] = 1585,
  [SMALL_STATE(61)] = 1605,
  [SMALL_STATE(62)] = 1625,
  [SMALL_STATE(63)] = 1645,
  [SMALL_STATE(64)] = 1665,
  [SMALL_STATE(65)] = 1685,
  [SMALL_STATE(66)] = 1702,
  [SMALL_STATE(67)] = 1719,
  [SMALL_STATE(68)] = 1736,
  [SMALL_STATE(69)] = 1753,
  [SMALL_STATE(70)] = 1770,
  [SMALL_STATE(71)] = 1787,
  [SMALL_STATE(72)] = 1802,
  [SMALL_STATE(73)] = 1817,
  [SMALL_STATE(74)] = 1834,
  [SMALL_STATE(75)] = 1848,
  [SMALL_STATE(76)] = 1862,
  [SMALL_STATE(77)] = 1876,
  [SMALL_STATE(78)] = 1890,
  [SMALL_STATE(79)] = 1904,
  [SMALL_STATE(80)] = 1918,
  [SMALL_STATE(81)] = 1932,
  [SMALL_STATE(82)] = 1946,
  [SMALL_STATE(83)] = 1960,
  [SMALL_STATE(84)] = 1974,
  [SMALL_STATE(85)] = 1988,
  [SMALL_STATE(86)] = 2002,
  [SMALL_STATE(87)] = 2016,
  [SMALL_STATE(88)] = 2030,
  [SMALL_STATE(89)] = 2044,
  [SMALL_STATE(90)] = 2058,
  [SMALL_STATE(91)] = 2072,
  [SMALL_STATE(92)] = 2086,
  [SMALL_STATE(93)] = 2100,
  [SMALL_STATE(94)] = 2114,
  [SMALL_STATE(95)] = 2128,
  [SMALL_STATE(96)] = 2132,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2), SHIFT_REPEAT(84),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 2),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 1, .production_id = 5),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 1, .production_id = 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 4, .production_id = 21),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 4, .production_id = 21),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(77),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeVariant, 1, .production_id = 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeVariant, 1, .production_id = 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 2, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 5, .production_id = 20),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 5, .production_id = 20),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 9),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 9),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 10),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 10),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2), SHIFT_REPEAT(44),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2), SHIFT_REPEAT(77),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__innerOrAlias, 1, .production_id = 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__innerOrAlias, 1, .production_id = 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 8),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 14),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 14),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 15),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 15),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__innerOrAlias, 2, .production_id = 6),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__innerOrAlias, 2, .production_id = 6),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 16),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 16),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 2), SHIFT_REPEAT(16),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat2, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 3, .production_id = 4),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 2), SHIFT_REPEAT(79),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat1, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 3, .production_id = 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat1, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat2, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeVariant, 2, .production_id = 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeVariant, 2, .production_id = 7),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2), SHIFT_REPEAT(44),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2), SHIFT_REPEAT(66),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2), SHIFT_REPEAT(46),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 12),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 11),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 4, .production_id = 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 19),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 24),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 18),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 17),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [271] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 22),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 23),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 9, .production_id = 27),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 25),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 26),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docComment, 3),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ridotto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
