#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 32

enum {
  sym_ident = 1,
  sym__lparen = 2,
  sym__rparen = 3,
  sym__lbrack = 4,
  sym__rbrack = 5,
  sym__lbrace = 6,
  sym__rbrace = 7,
  sym__comma = 8,
  sym__period = 9,
  sym__eq = 10,
  sym__colon = 11,
  sym__arrow = 12,
  sym__pound = 13,
  sym__poundPound = 14,
  sym__newline = 15,
  sym__typeKw = 16,
  sym__asyncKw = 17,
  sym__constKw = 18,
  sym__exportKw = 19,
  sym__builtinKw = 20,
  sym__funcKw = 21,
  sym__classKw = 22,
  sym__returnKw = 23,
  sym__breakKw = 24,
  sym__continueKw = 25,
  sym__letKw = 26,
  aux_sym__comment_token1 = 27,
  anon_sym_DASH = 28,
  anon_sym_PLUS = 29,
  anon_sym_BANG = 30,
  anon_sym_AT = 31,
  anon_sym_STAR = 32,
  anon_sym_SLASH = 33,
  sym_number = 34,
  sym_string = 35,
  sym_bool = 36,
  sym_source_file = 37,
  sym__comment = 38,
  sym_docComment = 39,
  sym__typeArgs = 40,
  sym_typeExpr = 41,
  sym_typeName = 42,
  sym_typeDecl = 43,
  sym__innerOrAlias = 44,
  sym__typeInner = 45,
  sym_typeVariant = 46,
  sym_typeAnnotated = 47,
  sym_funcHead = 48,
  sym_func = 49,
  sym_block = 50,
  sym__stmt = 51,
  sym_binding = 52,
  sym__expr = 53,
  sym__paren = 54,
  sym_dotAccess = 55,
  sym_unary = 56,
  sym_binary = 57,
  sym_arrayIndex = 58,
  sym_klass = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym__typeArgs_repeat1 = 61,
  aux_sym_typeName_repeat1 = 62,
  aux_sym__typeInner_repeat1 = 63,
  aux_sym__typeInner_repeat2 = 64,
  aux_sym__typeInner_repeat3 = 65,
  aux_sym_funcHead_repeat1 = 66,
  aux_sym_funcHead_repeat2 = 67,
  aux_sym_block_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [sym__lparen] = "_lparen",
  [sym__rparen] = "_rparen",
  [sym__lbrack] = "_lbrack",
  [sym__rbrack] = "_rbrack",
  [sym__lbrace] = "_lbrace",
  [sym__rbrace] = "_rbrace",
  [sym__comma] = "_comma",
  [sym__period] = "_period",
  [sym__eq] = "_eq",
  [sym__colon] = "_colon",
  [sym__arrow] = "_arrow",
  [sym__pound] = "_pound",
  [sym__poundPound] = "_poundPound",
  [sym__newline] = "_newline",
  [sym__typeKw] = "_typeKw",
  [sym__asyncKw] = "_asyncKw",
  [sym__constKw] = "_constKw",
  [sym__exportKw] = "_exportKw",
  [sym__builtinKw] = "_builtinKw",
  [sym__funcKw] = "_funcKw",
  [sym__classKw] = "_classKw",
  [sym__returnKw] = "_returnKw",
  [sym__breakKw] = "_breakKw",
  [sym__continueKw] = "_continueKw",
  [sym__letKw] = "_letKw",
  [aux_sym__comment_token1] = "_comment_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_AT] = "@",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_bool] = "bool",
  [sym_source_file] = "source_file",
  [sym__comment] = "_comment",
  [sym_docComment] = "docComment",
  [sym__typeArgs] = "_typeArgs",
  [sym_typeExpr] = "typeExpr",
  [sym_typeName] = "typeName",
  [sym_typeDecl] = "typeDecl",
  [sym__innerOrAlias] = "_innerOrAlias",
  [sym__typeInner] = "_typeInner",
  [sym_typeVariant] = "typeVariant",
  [sym_typeAnnotated] = "typeAnnotated",
  [sym_funcHead] = "funcHead",
  [sym_func] = "func",
  [sym_block] = "block",
  [sym__stmt] = "_stmt",
  [sym_binding] = "binding",
  [sym__expr] = "_expr",
  [sym__paren] = "_paren",
  [sym_dotAccess] = "dotAccess",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_arrayIndex] = "arrayIndex",
  [sym_klass] = "klass",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__typeArgs_repeat1] = "_typeArgs_repeat1",
  [aux_sym_typeName_repeat1] = "typeName_repeat1",
  [aux_sym__typeInner_repeat1] = "_typeInner_repeat1",
  [aux_sym__typeInner_repeat2] = "_typeInner_repeat2",
  [aux_sym__typeInner_repeat3] = "_typeInner_repeat3",
  [aux_sym_funcHead_repeat1] = "funcHead_repeat1",
  [aux_sym_funcHead_repeat2] = "funcHead_repeat2",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [sym__lparen] = sym__lparen,
  [sym__rparen] = sym__rparen,
  [sym__lbrack] = sym__lbrack,
  [sym__rbrack] = sym__rbrack,
  [sym__lbrace] = sym__lbrace,
  [sym__rbrace] = sym__rbrace,
  [sym__comma] = sym__comma,
  [sym__period] = sym__period,
  [sym__eq] = sym__eq,
  [sym__colon] = sym__colon,
  [sym__arrow] = sym__arrow,
  [sym__pound] = sym__pound,
  [sym__poundPound] = sym__poundPound,
  [sym__newline] = sym__newline,
  [sym__typeKw] = sym__typeKw,
  [sym__asyncKw] = sym__asyncKw,
  [sym__constKw] = sym__constKw,
  [sym__exportKw] = sym__exportKw,
  [sym__builtinKw] = sym__builtinKw,
  [sym__funcKw] = sym__funcKw,
  [sym__classKw] = sym__classKw,
  [sym__returnKw] = sym__returnKw,
  [sym__breakKw] = sym__breakKw,
  [sym__continueKw] = sym__continueKw,
  [sym__letKw] = sym__letKw,
  [aux_sym__comment_token1] = aux_sym__comment_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_bool] = sym_bool,
  [sym_source_file] = sym_source_file,
  [sym__comment] = sym__comment,
  [sym_docComment] = sym_docComment,
  [sym__typeArgs] = sym__typeArgs,
  [sym_typeExpr] = sym_typeExpr,
  [sym_typeName] = sym_typeName,
  [sym_typeDecl] = sym_typeDecl,
  [sym__innerOrAlias] = sym__innerOrAlias,
  [sym__typeInner] = sym__typeInner,
  [sym_typeVariant] = sym_typeVariant,
  [sym_typeAnnotated] = sym_typeAnnotated,
  [sym_funcHead] = sym_funcHead,
  [sym_func] = sym_func,
  [sym_block] = sym_block,
  [sym__stmt] = sym__stmt,
  [sym_binding] = sym_binding,
  [sym__expr] = sym__expr,
  [sym__paren] = sym__paren,
  [sym_dotAccess] = sym_dotAccess,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_arrayIndex] = sym_arrayIndex,
  [sym_klass] = sym_klass,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__typeArgs_repeat1] = aux_sym__typeArgs_repeat1,
  [aux_sym_typeName_repeat1] = aux_sym_typeName_repeat1,
  [aux_sym__typeInner_repeat1] = aux_sym__typeInner_repeat1,
  [aux_sym__typeInner_repeat2] = aux_sym__typeInner_repeat2,
  [aux_sym__typeInner_repeat3] = aux_sym__typeInner_repeat3,
  [aux_sym_funcHead_repeat1] = aux_sym_funcHead_repeat1,
  [aux_sym_funcHead_repeat2] = aux_sym_funcHead_repeat2,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym__lparen] = {
    .visible = false,
    .named = true,
  },
  [sym__rparen] = {
    .visible = false,
    .named = true,
  },
  [sym__lbrack] = {
    .visible = false,
    .named = true,
  },
  [sym__rbrack] = {
    .visible = false,
    .named = true,
  },
  [sym__lbrace] = {
    .visible = false,
    .named = true,
  },
  [sym__rbrace] = {
    .visible = false,
    .named = true,
  },
  [sym__comma] = {
    .visible = false,
    .named = true,
  },
  [sym__period] = {
    .visible = false,
    .named = true,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [sym__colon] = {
    .visible = false,
    .named = true,
  },
  [sym__arrow] = {
    .visible = false,
    .named = true,
  },
  [sym__pound] = {
    .visible = false,
    .named = true,
  },
  [sym__poundPound] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__typeKw] = {
    .visible = false,
    .named = true,
  },
  [sym__asyncKw] = {
    .visible = false,
    .named = true,
  },
  [sym__constKw] = {
    .visible = false,
    .named = true,
  },
  [sym__exportKw] = {
    .visible = false,
    .named = true,
  },
  [sym__builtinKw] = {
    .visible = false,
    .named = true,
  },
  [sym__funcKw] = {
    .visible = false,
    .named = true,
  },
  [sym__classKw] = {
    .visible = false,
    .named = true,
  },
  [sym__returnKw] = {
    .visible = false,
    .named = true,
  },
  [sym__breakKw] = {
    .visible = false,
    .named = true,
  },
  [sym__continueKw] = {
    .visible = false,
    .named = true,
  },
  [sym__letKw] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_docComment] = {
    .visible = true,
    .named = true,
  },
  [sym__typeArgs] = {
    .visible = false,
    .named = true,
  },
  [sym_typeExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_typeName] = {
    .visible = true,
    .named = true,
  },
  [sym_typeDecl] = {
    .visible = true,
    .named = true,
  },
  [sym__innerOrAlias] = {
    .visible = false,
    .named = true,
  },
  [sym__typeInner] = {
    .visible = false,
    .named = true,
  },
  [sym_typeVariant] = {
    .visible = true,
    .named = true,
  },
  [sym_typeAnnotated] = {
    .visible = true,
    .named = true,
  },
  [sym_funcHead] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__paren] = {
    .visible = false,
    .named = true,
  },
  [sym_dotAccess] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_arrayIndex] = {
    .visible = true,
    .named = true,
  },
  [sym_klass] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeArgs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeName_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeInner_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_args = 2,
  field_array = 3,
  field_body = 4,
  field_instantiate = 5,
  field_lhs = 6,
  field_method = 7,
  field_name = 8,
  field_offset = 9,
  field_op = 10,
  field_property = 11,
  field_return = 12,
  field_rhs = 13,
  field_type = 14,
  field_value = 15,
  field_variant = 16,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_args] = "args",
  [field_array] = "array",
  [field_body] = "body",
  [field_instantiate] = "instantiate",
  [field_lhs] = "lhs",
  [field_method] = "method",
  [field_name] = "name",
  [field_offset] = "offset",
  [field_op] = "op",
  [field_property] = "property",
  [field_return] = "return",
  [field_rhs] = "rhs",
  [field_type] = "type",
  [field_value] = "value",
  [field_variant] = "variant",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 5},
  [4] = {.index = 7, .length = 3},
  [5] = {.index = 10, .length = 1},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 5},
  [8] = {.index = 18, .length = 1},
  [9] = {.index = 19, .length = 1},
  [10] = {.index = 20, .length = 1},
  [11] = {.index = 21, .length = 2},
  [12] = {.index = 23, .length = 1},
  [13] = {.index = 24, .length = 2},
  [14] = {.index = 26, .length = 2},
  [15] = {.index = 28, .length = 2},
  [16] = {.index = 30, .length = 2},
  [17] = {.index = 32, .length = 3},
  [18] = {.index = 35, .length = 3},
  [19] = {.index = 38, .length = 2},
  [20] = {.index = 40, .length = 2},
  [21] = {.index = 42, .length = 3},
  [22] = {.index = 45, .length = 4},
  [23] = {.index = 49, .length = 4},
  [24] = {.index = 53, .length = 1},
  [25] = {.index = 54, .length = 3},
  [26] = {.index = 57, .length = 3},
  [27] = {.index = 60, .length = 5},
  [28] = {.index = 65, .length = 3},
  [29] = {.index = 68, .length = 4},
  [30] = {.index = 72, .length = 2},
  [31] = {.index = 74, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_body, 1},
  [2] =
    {field_alias, 2, .inherited = true},
    {field_method, 2, .inherited = true},
    {field_name, 1},
    {field_property, 2, .inherited = true},
    {field_variant, 2, .inherited = true},
  [7] =
    {field_method, 0, .inherited = true},
    {field_property, 0, .inherited = true},
    {field_variant, 0, .inherited = true},
  [10] =
    {field_name, 0},
  [11] =
    {field_alias, 0},
    {field_alias, 1},
  [13] =
    {field_alias, 1, .inherited = true},
    {field_method, 1, .inherited = true},
    {field_name, 0},
    {field_property, 1, .inherited = true},
    {field_variant, 1, .inherited = true},
  [18] =
    {field_property, 1},
  [19] =
    {field_variant, 1},
  [20] =
    {field_method, 1},
  [21] =
    {field_args, 3},
    {field_name, 1},
  [23] =
    {field_name, 2},
  [24] =
    {field_name, 0},
    {field_type, 2},
  [26] =
    {field_property, 1},
    {field_variant, 2},
  [28] =
    {field_method, 2},
    {field_property, 1},
  [30] =
    {field_method, 2},
    {field_variant, 1},
  [32] =
    {field_name, 1},
    {field_return, 4},
    {field_return, 5},
  [35] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
  [38] =
    {field_name, 1},
    {field_value, 3},
  [40] =
    {field_args, 4},
    {field_name, 2},
  [42] =
    {field_method, 3},
    {field_property, 1},
    {field_variant, 2},
  [45] =
    {field_instantiate, 1},
    {field_instantiate, 2},
    {field_instantiate, 3},
    {field_name, 0},
  [49] =
    {field_args, 3},
    {field_name, 1},
    {field_return, 5},
    {field_return, 6},
  [53] =
    {field_op, 0},
  [54] =
    {field_name, 2},
    {field_return, 5},
    {field_return, 6},
  [57] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
  [60] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
    {field_return, 6},
    {field_return, 7},
  [65] =
    {field_lhs, 0},
    {field_op, 1},
    {field_rhs, 2},
  [68] =
    {field_args, 4},
    {field_name, 2},
    {field_return, 6},
    {field_return, 7},
  [72] =
    {field_array, 0},
    {field_offset, 2},
  [74] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
    {field_return, 7},
    {field_return, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(8);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '+') ADVANCE(32);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__lparen);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__rparen);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__lbrack);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__rbrack);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__lbrace);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__rbrace);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__comma);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__period);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__eq);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__colon);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__arrow);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__pound);
      if (lookahead == '#') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__pound);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__poundPound);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__poundPound);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(10);
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__letKw);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'k') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__funcKw);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__typeKw);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__asyncKw);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__breakKw);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__classKw);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__constKw);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__exportKw);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__returnKw);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__builtinKw);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__continueKw);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 27},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 27},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {(TSStateId)(-1)},
  [123] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym__comment] = STATE(0),
    [sym_docComment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym__lparen] = ACTIONS(1),
    [sym__rparen] = ACTIONS(1),
    [sym__lbrack] = ACTIONS(1),
    [sym__rbrack] = ACTIONS(1),
    [sym__lbrace] = ACTIONS(1),
    [sym__rbrace] = ACTIONS(1),
    [sym__comma] = ACTIONS(1),
    [sym__period] = ACTIONS(1),
    [sym__eq] = ACTIONS(1),
    [sym__colon] = ACTIONS(1),
    [sym__arrow] = ACTIONS(1),
    [sym__pound] = ACTIONS(3),
    [sym__poundPound] = ACTIONS(5),
    [sym__typeKw] = ACTIONS(1),
    [sym__asyncKw] = ACTIONS(1),
    [sym__constKw] = ACTIONS(1),
    [sym__exportKw] = ACTIONS(1),
    [sym__builtinKw] = ACTIONS(1),
    [sym__funcKw] = ACTIONS(1),
    [sym__classKw] = ACTIONS(1),
    [sym__returnKw] = ACTIONS(1),
    [sym__breakKw] = ACTIONS(1),
    [sym__continueKw] = ACTIONS(1),
    [sym__letKw] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_bool] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(113),
    [sym__comment] = STATE(1),
    [sym_docComment] = STATE(1),
    [sym_typeDecl] = STATE(54),
    [sym_funcHead] = STATE(94),
    [sym_func] = STATE(54),
    [sym_klass] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_funcHead_repeat1] = STATE(63),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym__pound] = ACTIONS(3),
    [sym__poundPound] = ACTIONS(5),
    [sym__typeKw] = ACTIONS(9),
    [sym__asyncKw] = ACTIONS(11),
    [sym__constKw] = ACTIONS(11),
    [sym__exportKw] = ACTIONS(11),
    [sym__builtinKw] = ACTIONS(11),
    [sym__funcKw] = ACTIONS(13),
    [sym__classKw] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(21), 1,
      sym__period,
    STATE(2), 3,
      sym__comment,
      sym_docComment,
      aux_sym_typeName_repeat1,
    ACTIONS(19), 9,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym__letKw,
      sym_ident,
    ACTIONS(17), 11,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [39] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(3), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(19), 9,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym__letKw,
      sym_ident,
    ACTIONS(17), 12,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
      sym__period,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [75] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(5), 1,
      aux_sym_typeName_repeat1,
    STATE(4), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(24), 7,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(26), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [111] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(2), 1,
      aux_sym_typeName_repeat1,
    STATE(5), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(30), 7,
      ts_builtin_sym_end,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(32), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [147] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(46), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(6), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [191] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(47), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(7), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [235] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(61), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(8), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [279] = 15,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(48), 1,
      sym__rbrace,
    ACTIONS(52), 1,
      sym__funcKw,
    STATE(13), 1,
      aux_sym__typeInner_repeat1,
    STATE(18), 1,
      aux_sym__typeInner_repeat2,
    STATE(33), 1,
      aux_sym__typeInner_repeat3,
    STATE(58), 1,
      sym_typeAnnotated,
    STATE(59), 1,
      sym_typeVariant,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(9), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(50), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [329] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(58), 1,
      sym__lbrack,
    STATE(10), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(54), 6,
      ts_builtin_sym_end,
      sym__rparen,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(56), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [361] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(57), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(11), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [405] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(51), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(12), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [449] = 15,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(52), 1,
      sym__funcKw,
    ACTIONS(60), 1,
      sym__rbrace,
    STATE(19), 1,
      aux_sym__typeInner_repeat2,
    STATE(30), 1,
      aux_sym__typeInner_repeat3,
    STATE(41), 1,
      aux_sym__typeInner_repeat1,
    STATE(58), 1,
      sym_typeAnnotated,
    STATE(59), 1,
      sym_typeVariant,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(13), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(50), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [499] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(36), 1,
      sym__lparen,
    ACTIONS(44), 1,
      sym_bool,
    STATE(40), 1,
      sym_arrayIndex,
    STATE(60), 1,
      sym__expr,
    ACTIONS(38), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(40), 2,
      anon_sym_BANG,
      anon_sym_AT,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(14), 2,
      sym__comment,
      sym_docComment,
    STATE(44), 4,
      sym__paren,
      sym_dotAccess,
      sym_unary,
      sym_binary,
  [543] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(15), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(62), 6,
      ts_builtin_sym_end,
      sym__rparen,
      sym__rbrack,
      sym__lbrace,
      sym__rbrace,
      sym__comma,
    ACTIONS(64), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [572] = 11,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      sym__typeKw,
    ACTIONS(74), 1,
      sym__funcKw,
    ACTIONS(77), 1,
      sym__classKw,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(16), 3,
      sym__comment,
      sym_docComment,
      aux_sym_source_file_repeat1,
    STATE(54), 3,
      sym_typeDecl,
      sym_func,
      sym_klass,
    ACTIONS(71), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [613] = 12,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(9), 1,
      sym__typeKw,
    ACTIONS(13), 1,
      sym__funcKw,
    ACTIONS(15), 1,
      sym__classKw,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(17), 2,
      sym__comment,
      sym_docComment,
    STATE(54), 3,
      sym_typeDecl,
      sym_func,
      sym_klass,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [656] = 13,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(52), 1,
      sym__funcKw,
    ACTIONS(82), 1,
      sym_ident,
    ACTIONS(84), 1,
      sym__rbrace,
    STATE(26), 1,
      aux_sym__typeInner_repeat3,
    STATE(45), 1,
      aux_sym__typeInner_repeat2,
    STATE(59), 1,
      sym_typeVariant,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(18), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(50), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [700] = 13,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(52), 1,
      sym__funcKw,
    ACTIONS(82), 1,
      sym_ident,
    ACTIONS(86), 1,
      sym__rbrace,
    STATE(34), 1,
      aux_sym__typeInner_repeat3,
    STATE(45), 1,
      aux_sym__typeInner_repeat2,
    STATE(59), 1,
      sym_typeVariant,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(19), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(50), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [744] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(90), 1,
      sym__lbrace,
    ACTIONS(92), 1,
      sym__rbrace,
    ACTIONS(94), 1,
      sym__eq,
    ACTIONS(96), 1,
      sym__colon,
    STATE(27), 1,
      sym__typeInner,
    STATE(56), 1,
      sym__innerOrAlias,
    STATE(20), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(88), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [781] = 8,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(90), 1,
      sym__lbrace,
    ACTIONS(94), 1,
      sym__eq,
    STATE(27), 1,
      sym__typeInner,
    STATE(53), 1,
      sym__innerOrAlias,
    STATE(21), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(98), 8,
      ts_builtin_sym_end,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [814] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(2), 1,
      aux_sym_typeName_repeat1,
    STATE(22), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(100), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [842] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(28), 1,
      sym__period,
    STATE(22), 1,
      aux_sym_typeName_repeat1,
    STATE(23), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(102), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [870] = 9,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(90), 1,
      sym__lbrace,
    ACTIONS(92), 1,
      sym__rbrace,
    ACTIONS(94), 1,
      sym__eq,
    STATE(27), 1,
      sym__typeInner,
    STATE(56), 1,
      sym__innerOrAlias,
    STATE(24), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(88), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [904] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(25), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(106), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [929] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      sym__funcKw,
    ACTIONS(108), 1,
      sym__rbrace,
    STATE(28), 1,
      aux_sym__typeInner_repeat3,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(26), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [964] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(27), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(112), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [989] = 9,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(114), 1,
      sym__rbrace,
    ACTIONS(119), 1,
      sym__funcKw,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(28), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat3,
    ACTIONS(116), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1022] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(29), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(124), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1047] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      sym__funcKw,
    ACTIONS(126), 1,
      sym__rbrace,
    STATE(28), 1,
      aux_sym__typeInner_repeat3,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(30), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1082] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(31), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(130), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1107] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(32), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(134), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1132] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      sym__funcKw,
    ACTIONS(136), 1,
      sym__rbrace,
    STATE(28), 1,
      aux_sym__typeInner_repeat3,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(33), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1167] = 10,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(13), 1,
      sym__funcKw,
    ACTIONS(138), 1,
      sym__rbrace,
    STATE(28), 1,
      aux_sym__typeInner_repeat3,
    STATE(62), 1,
      sym_func,
    STATE(63), 1,
      aux_sym_funcHead_repeat1,
    STATE(94), 1,
      sym_funcHead,
    STATE(34), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1202] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(35), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(142), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1227] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(36), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(146), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1252] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(37), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(150), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1277] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(38), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(154), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1302] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      sym__rbrace,
    STATE(39), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(158), 8,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
      sym_ident,
  [1327] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(40), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(160), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1349] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(162), 1,
      sym_ident,
    ACTIONS(165), 1,
      sym__rbrace,
    STATE(58), 1,
      sym_typeAnnotated,
    STATE(41), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat1,
    ACTIONS(167), 5,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
  [1377] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(42), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(171), 3,
      sym__rparen,
      sym__rbrace,
      sym__comma,
    ACTIONS(169), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [1401] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(43), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(173), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1423] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(44), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(102), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1445] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(175), 1,
      sym_ident,
    ACTIONS(178), 1,
      sym__rbrace,
    STATE(59), 1,
      sym_typeVariant,
    STATE(45), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeInner_repeat2,
    ACTIONS(180), 5,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
  [1473] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    STATE(46), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(182), 8,
      sym__rparen,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1497] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    ACTIONS(186), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(47), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(182), 6,
      sym__rparen,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1523] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(48), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(188), 9,
      ts_builtin_sym_end,
      sym__rbrace,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1545] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(49), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(190), 9,
      sym__rparen,
      sym__lbrack,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1567] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(50), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(192), 9,
      ts_builtin_sym_end,
      sym__rbrace,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1589] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    STATE(51), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(194), 8,
      sym__rparen,
      sym__rbrack,
      sym__rbrace,
      sym__letKw,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1613] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(52), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(196), 9,
      ts_builtin_sym_end,
      sym__rbrace,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1635] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(53), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(198), 8,
      ts_builtin_sym_end,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1656] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(54), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(200), 8,
      ts_builtin_sym_end,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1677] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(55), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(202), 8,
      ts_builtin_sym_end,
      sym__typeKw,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym__classKw,
  [1698] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(206), 1,
      sym__rbrace,
    STATE(56), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(204), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [1720] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    ACTIONS(186), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(208), 2,
      sym__rbrace,
      sym__letKw,
    ACTIONS(210), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(57), 2,
      sym__comment,
      sym_docComment,
  [1746] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(214), 1,
      sym__rbrace,
    STATE(58), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(212), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [1768] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(218), 1,
      sym__rbrace,
    STATE(59), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(216), 6,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
      sym_ident,
  [1790] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    ACTIONS(220), 1,
      sym__rparen,
    ACTIONS(186), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(210), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(60), 2,
      sym__comment,
      sym_docComment,
  [1815] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(184), 1,
      sym__lbrack,
    ACTIONS(222), 1,
      sym__rbrack,
    ACTIONS(186), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(210), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(61), 2,
      sym__comment,
      sym_docComment,
  [1840] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(62), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(224), 6,
      sym__rbrace,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
  [1859] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(226), 1,
      sym__funcKw,
    STATE(64), 1,
      aux_sym_funcHead_repeat1,
    STATE(63), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(11), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1882] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(231), 1,
      sym__funcKw,
    STATE(64), 3,
      sym__comment,
      sym_docComment,
      aux_sym_funcHead_repeat1,
    ACTIONS(228), 4,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
  [1903] = 8,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(233), 1,
      sym__rbrace,
    ACTIONS(235), 1,
      sym__letKw,
    STATE(67), 1,
      aux_sym_block_repeat1,
    STATE(90), 1,
      sym_binding,
    STATE(99), 1,
      sym__stmt,
    STATE(65), 2,
      sym__comment,
      sym_docComment,
  [1929] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    STATE(66), 2,
      sym__comment,
      sym_docComment,
    ACTIONS(237), 5,
      sym__asyncKw,
      sym__constKw,
      sym__exportKw,
      sym__builtinKw,
      sym__funcKw,
  [1947] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(239), 1,
      sym__rbrace,
    ACTIONS(241), 1,
      sym__letKw,
    STATE(90), 1,
      sym_binding,
    STATE(99), 1,
      sym__stmt,
    STATE(67), 3,
      sym__comment,
      sym_docComment,
      aux_sym_block_repeat1,
  [1971] = 8,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(235), 1,
      sym__letKw,
    ACTIONS(244), 1,
      sym__rbrace,
    STATE(65), 1,
      aux_sym_block_repeat1,
    STATE(90), 1,
      sym_binding,
    STATE(99), 1,
      sym__stmt,
    STATE(68), 2,
      sym__comment,
      sym_docComment,
  [1997] = 7,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(83), 1,
      sym_typeExpr,
    STATE(105), 1,
      sym__typeArgs,
    STATE(69), 2,
      sym__comment,
      sym_docComment,
  [2020] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(248), 1,
      sym__rbrack,
    ACTIONS(250), 1,
      sym__comma,
    STATE(77), 1,
      aux_sym__typeArgs_repeat1,
    STATE(70), 2,
      sym__comment,
      sym_docComment,
  [2040] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(110), 1,
      sym_typeExpr,
    STATE(71), 2,
      sym__comment,
      sym_docComment,
  [2060] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(103), 1,
      sym_typeExpr,
    STATE(72), 2,
      sym__comment,
      sym_docComment,
  [2080] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(116), 1,
      sym_typeExpr,
    STATE(73), 2,
      sym__comment,
      sym_docComment,
  [2100] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(252), 1,
      sym__rparen,
    ACTIONS(254), 1,
      sym__comma,
    STATE(75), 1,
      aux_sym_funcHead_repeat2,
    STATE(74), 2,
      sym__comment,
      sym_docComment,
  [2120] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(254), 1,
      sym__comma,
    ACTIONS(256), 1,
      sym__rparen,
    STATE(88), 1,
      aux_sym_funcHead_repeat2,
    STATE(75), 2,
      sym__comment,
      sym_docComment,
  [2140] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(258), 1,
      sym_ident,
    ACTIONS(260), 1,
      sym__rparen,
    STATE(78), 1,
      sym_typeAnnotated,
    STATE(76), 2,
      sym__comment,
      sym_docComment,
  [2160] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(262), 1,
      sym__rbrack,
    ACTIONS(264), 1,
      sym__comma,
    STATE(77), 3,
      sym__comment,
      sym_docComment,
      aux_sym__typeArgs_repeat1,
  [2178] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(254), 1,
      sym__comma,
    ACTIONS(267), 1,
      sym__rparen,
    STATE(84), 1,
      aux_sym_funcHead_repeat2,
    STATE(78), 2,
      sym__comment,
      sym_docComment,
  [2198] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(120), 1,
      sym_typeExpr,
    STATE(79), 2,
      sym__comment,
      sym_docComment,
  [2218] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(42), 1,
      sym_typeExpr,
    STATE(80), 2,
      sym__comment,
      sym_docComment,
  [2238] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(115), 1,
      sym_typeExpr,
    STATE(81), 2,
      sym__comment,
      sym_docComment,
  [2258] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(96), 1,
      sym_typeExpr,
    STATE(82), 2,
      sym__comment,
      sym_docComment,
  [2278] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(250), 1,
      sym__comma,
    ACTIONS(269), 1,
      sym__rbrack,
    STATE(70), 1,
      aux_sym__typeArgs_repeat1,
    STATE(83), 2,
      sym__comment,
      sym_docComment,
  [2298] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(254), 1,
      sym__comma,
    ACTIONS(271), 1,
      sym__rparen,
    STATE(88), 1,
      aux_sym_funcHead_repeat2,
    STATE(84), 2,
      sym__comment,
      sym_docComment,
  [2318] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(104), 1,
      sym_typeExpr,
    STATE(85), 2,
      sym__comment,
      sym_docComment,
  [2338] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(246), 1,
      sym_ident,
    STATE(10), 1,
      sym_typeName,
    STATE(37), 1,
      sym_typeExpr,
    STATE(86), 2,
      sym__comment,
      sym_docComment,
  [2358] = 6,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(258), 1,
      sym_ident,
    ACTIONS(273), 1,
      sym__rparen,
    STATE(74), 1,
      sym_typeAnnotated,
    STATE(87), 2,
      sym__comment,
      sym_docComment,
  [2378] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(275), 1,
      sym__rparen,
    ACTIONS(277), 1,
      sym__comma,
    STATE(88), 3,
      sym__comment,
      sym_docComment,
      aux_sym_funcHead_repeat2,
  [2396] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(280), 1,
      sym__lbrace,
    ACTIONS(282), 1,
      sym__arrow,
    STATE(89), 2,
      sym__comment,
      sym_docComment,
  [2413] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(284), 2,
      sym__rbrace,
      sym__letKw,
    STATE(90), 2,
      sym__comment,
      sym_docComment,
  [2428] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(286), 1,
      sym__lbrace,
    ACTIONS(288), 1,
      sym__arrow,
    STATE(91), 2,
      sym__comment,
      sym_docComment,
  [2445] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(290), 1,
      sym__lbrace,
    ACTIONS(292), 1,
      sym__arrow,
    STATE(92), 2,
      sym__comment,
      sym_docComment,
  [2462] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(258), 1,
      sym_ident,
    STATE(100), 1,
      sym_typeAnnotated,
    STATE(93), 2,
      sym__comment,
      sym_docComment,
  [2479] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(294), 1,
      sym__lbrace,
    STATE(52), 1,
      sym_block,
    STATE(94), 2,
      sym__comment,
      sym_docComment,
  [2496] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(296), 1,
      sym__lbrace,
    ACTIONS(298), 1,
      sym__arrow,
    STATE(95), 2,
      sym__comment,
      sym_docComment,
  [2513] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(262), 2,
      sym__rbrack,
      sym__comma,
    STATE(96), 2,
      sym__comment,
      sym_docComment,
  [2528] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(300), 1,
      sym__lbrace,
    ACTIONS(302), 1,
      sym__arrow,
    STATE(97), 2,
      sym__comment,
      sym_docComment,
  [2545] = 5,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(304), 1,
      sym__lbrace,
    ACTIONS(306), 1,
      sym__arrow,
    STATE(98), 2,
      sym__comment,
      sym_docComment,
  [2562] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(308), 2,
      sym__rbrace,
      sym__letKw,
    STATE(99), 2,
      sym__comment,
      sym_docComment,
  [2577] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(275), 2,
      sym__rparen,
      sym__comma,
    STATE(100), 2,
      sym__comment,
      sym_docComment,
  [2592] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(310), 1,
      sym_ident,
    STATE(101), 2,
      sym__comment,
      sym_docComment,
  [2606] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(312), 1,
      sym__poundPound,
    ACTIONS(314), 1,
      sym__newline,
    STATE(102), 2,
      sym__comment,
      sym_docComment,
  [2620] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(316), 1,
      sym__lbrace,
    STATE(103), 2,
      sym__comment,
      sym_docComment,
  [2634] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(318), 1,
      sym__lbrace,
    STATE(104), 2,
      sym__comment,
      sym_docComment,
  [2648] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(320), 1,
      sym__rbrack,
    STATE(105), 2,
      sym__comment,
      sym_docComment,
  [2662] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(312), 1,
      sym__poundPound,
    ACTIONS(322), 1,
      aux_sym__comment_token1,
    STATE(106), 2,
      sym__comment,
      sym_docComment,
  [2676] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(312), 1,
      sym__poundPound,
    ACTIONS(324), 1,
      sym__newline,
    STATE(107), 2,
      sym__comment,
      sym_docComment,
  [2690] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(326), 1,
      sym_ident,
    STATE(108), 2,
      sym__comment,
      sym_docComment,
  [2704] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(312), 1,
      sym__poundPound,
    ACTIONS(328), 1,
      aux_sym__comment_token1,
    STATE(109), 2,
      sym__comment,
      sym_docComment,
  [2718] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(330), 1,
      sym__lbrace,
    STATE(110), 2,
      sym__comment,
      sym_docComment,
  [2732] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(332), 1,
      sym__lparen,
    STATE(111), 2,
      sym__comment,
      sym_docComment,
  [2746] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(334), 1,
      sym_ident,
    STATE(112), 2,
      sym__comment,
      sym_docComment,
  [2760] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
    STATE(113), 2,
      sym__comment,
      sym_docComment,
  [2774] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(338), 1,
      sym_ident,
    STATE(114), 2,
      sym__comment,
      sym_docComment,
  [2788] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(340), 1,
      sym__lbrace,
    STATE(115), 2,
      sym__comment,
      sym_docComment,
  [2802] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(342), 1,
      sym__lbrace,
    STATE(116), 2,
      sym__comment,
      sym_docComment,
  [2816] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(344), 1,
      sym__eq,
    STATE(117), 2,
      sym__comment,
      sym_docComment,
  [2830] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(346), 1,
      sym__lparen,
    STATE(118), 2,
      sym__comment,
      sym_docComment,
  [2844] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(96), 1,
      sym__colon,
    STATE(119), 2,
      sym__comment,
      sym_docComment,
  [2858] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(348), 1,
      sym__lbrace,
    STATE(120), 2,
      sym__comment,
      sym_docComment,
  [2872] = 4,
    ACTIONS(3), 1,
      sym__pound,
    ACTIONS(5), 1,
      sym__poundPound,
    ACTIONS(350), 1,
      sym_ident,
    STATE(121), 2,
      sym__comment,
      sym_docComment,
  [2886] = 1,
    ACTIONS(352), 1,
      ts_builtin_sym_end,
  [2890] = 1,
    ACTIONS(354), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 75,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 235,
  [SMALL_STATE(9)] = 279,
  [SMALL_STATE(10)] = 329,
  [SMALL_STATE(11)] = 361,
  [SMALL_STATE(12)] = 405,
  [SMALL_STATE(13)] = 449,
  [SMALL_STATE(14)] = 499,
  [SMALL_STATE(15)] = 543,
  [SMALL_STATE(16)] = 572,
  [SMALL_STATE(17)] = 613,
  [SMALL_STATE(18)] = 656,
  [SMALL_STATE(19)] = 700,
  [SMALL_STATE(20)] = 744,
  [SMALL_STATE(21)] = 781,
  [SMALL_STATE(22)] = 814,
  [SMALL_STATE(23)] = 842,
  [SMALL_STATE(24)] = 870,
  [SMALL_STATE(25)] = 904,
  [SMALL_STATE(26)] = 929,
  [SMALL_STATE(27)] = 964,
  [SMALL_STATE(28)] = 989,
  [SMALL_STATE(29)] = 1022,
  [SMALL_STATE(30)] = 1047,
  [SMALL_STATE(31)] = 1082,
  [SMALL_STATE(32)] = 1107,
  [SMALL_STATE(33)] = 1132,
  [SMALL_STATE(34)] = 1167,
  [SMALL_STATE(35)] = 1202,
  [SMALL_STATE(36)] = 1227,
  [SMALL_STATE(37)] = 1252,
  [SMALL_STATE(38)] = 1277,
  [SMALL_STATE(39)] = 1302,
  [SMALL_STATE(40)] = 1327,
  [SMALL_STATE(41)] = 1349,
  [SMALL_STATE(42)] = 1377,
  [SMALL_STATE(43)] = 1401,
  [SMALL_STATE(44)] = 1423,
  [SMALL_STATE(45)] = 1445,
  [SMALL_STATE(46)] = 1473,
  [SMALL_STATE(47)] = 1497,
  [SMALL_STATE(48)] = 1523,
  [SMALL_STATE(49)] = 1545,
  [SMALL_STATE(50)] = 1567,
  [SMALL_STATE(51)] = 1589,
  [SMALL_STATE(52)] = 1613,
  [SMALL_STATE(53)] = 1635,
  [SMALL_STATE(54)] = 1656,
  [SMALL_STATE(55)] = 1677,
  [SMALL_STATE(56)] = 1698,
  [SMALL_STATE(57)] = 1720,
  [SMALL_STATE(58)] = 1746,
  [SMALL_STATE(59)] = 1768,
  [SMALL_STATE(60)] = 1790,
  [SMALL_STATE(61)] = 1815,
  [SMALL_STATE(62)] = 1840,
  [SMALL_STATE(63)] = 1859,
  [SMALL_STATE(64)] = 1882,
  [SMALL_STATE(65)] = 1903,
  [SMALL_STATE(66)] = 1929,
  [SMALL_STATE(67)] = 1947,
  [SMALL_STATE(68)] = 1971,
  [SMALL_STATE(69)] = 1997,
  [SMALL_STATE(70)] = 2020,
  [SMALL_STATE(71)] = 2040,
  [SMALL_STATE(72)] = 2060,
  [SMALL_STATE(73)] = 2080,
  [SMALL_STATE(74)] = 2100,
  [SMALL_STATE(75)] = 2120,
  [SMALL_STATE(76)] = 2140,
  [SMALL_STATE(77)] = 2160,
  [SMALL_STATE(78)] = 2178,
  [SMALL_STATE(79)] = 2198,
  [SMALL_STATE(80)] = 2218,
  [SMALL_STATE(81)] = 2238,
  [SMALL_STATE(82)] = 2258,
  [SMALL_STATE(83)] = 2278,
  [SMALL_STATE(84)] = 2298,
  [SMALL_STATE(85)] = 2318,
  [SMALL_STATE(86)] = 2338,
  [SMALL_STATE(87)] = 2358,
  [SMALL_STATE(88)] = 2378,
  [SMALL_STATE(89)] = 2396,
  [SMALL_STATE(90)] = 2413,
  [SMALL_STATE(91)] = 2428,
  [SMALL_STATE(92)] = 2445,
  [SMALL_STATE(93)] = 2462,
  [SMALL_STATE(94)] = 2479,
  [SMALL_STATE(95)] = 2496,
  [SMALL_STATE(96)] = 2513,
  [SMALL_STATE(97)] = 2528,
  [SMALL_STATE(98)] = 2545,
  [SMALL_STATE(99)] = 2562,
  [SMALL_STATE(100)] = 2577,
  [SMALL_STATE(101)] = 2592,
  [SMALL_STATE(102)] = 2606,
  [SMALL_STATE(103)] = 2620,
  [SMALL_STATE(104)] = 2634,
  [SMALL_STATE(105)] = 2648,
  [SMALL_STATE(106)] = 2662,
  [SMALL_STATE(107)] = 2676,
  [SMALL_STATE(108)] = 2690,
  [SMALL_STATE(109)] = 2704,
  [SMALL_STATE(110)] = 2718,
  [SMALL_STATE(111)] = 2732,
  [SMALL_STATE(112)] = 2746,
  [SMALL_STATE(113)] = 2760,
  [SMALL_STATE(114)] = 2774,
  [SMALL_STATE(115)] = 2788,
  [SMALL_STATE(116)] = 2802,
  [SMALL_STATE(117)] = 2816,
  [SMALL_STATE(118)] = 2830,
  [SMALL_STATE(119)] = 2844,
  [SMALL_STATE(120)] = 2858,
  [SMALL_STATE(121)] = 2872,
  [SMALL_STATE(122)] = 2886,
  [SMALL_STATE(123)] = 2890,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2), SHIFT_REPEAT(121),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 2),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 1, .production_id = 5),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 1, .production_id = 5),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 4, .production_id = 22),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 4, .production_id = 22),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(66),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(101),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeVariant, 1, .production_id = 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeVariant, 1, .production_id = 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 2, .production_id = 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotAccess, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 14),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 14),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__innerOrAlias, 1, .production_id = 4),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__innerOrAlias, 1, .production_id = 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2), SHIFT_REPEAT(66),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 2), SHIFT_REPEAT(101),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 9),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 9),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 10),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 10),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 5, .production_id = 21),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 5, .production_id = 21),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 2),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 15),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 15),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__innerOrAlias, 2, .production_id = 6),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__innerOrAlias, 2, .production_id = 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 4, .production_id = 16),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 4, .production_id = 16),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeInner, 3, .production_id = 8),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__typeInner, 3, .production_id = 8),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 1),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 2), SHIFT_REPEAT(119),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat1, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayIndex, 4, .production_id = 30),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 2), SHIFT_REPEAT(24),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat2, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, .production_id = 28),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paren, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, .production_id = 24),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2, .production_id = 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 3, .production_id = 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_klass, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeVariant, 2, .production_id = 7),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeVariant, 2, .production_id = 7),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, .production_id = 19),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat1, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat1, 1),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__typeInner_repeat2, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat2, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeInner_repeat3, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2), SHIFT_REPEAT(66),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2), SHIFT_REPEAT(82),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2), SHIFT_REPEAT(93),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 20),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 18),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 4, .production_id = 1),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 12),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 11),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 26),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 17),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 23),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [322] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 25),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 27),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 9, .production_id = 31),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 29),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 3),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docComment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ridotto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
