#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 27

enum {
  sym_ident = 1,
  anon_sym_COMMA = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_DOT = 5,
  anon_sym_type = 6,
  anon_sym_EQ = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_COLON = 10,
  anon_sym_async = 11,
  anon_sym_const = 12,
  anon_sym_export = 13,
  anon_sym_builtin = 14,
  anon_sym_func = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_DASH_GT = 18,
  sym_klass = 19,
  sym_source_file = 20,
  sym__typeArgs = 21,
  sym_typeExpr = 22,
  sym_typeName = 23,
  sym_typeDecl = 24,
  sym_typeInner = 25,
  sym_typeAnnotated = 26,
  sym_funcHead = 27,
  sym_func = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym__typeArgs_repeat1 = 30,
  aux_sym_typeName_repeat1 = 31,
  aux_sym_typeInner_repeat1 = 32,
  aux_sym_typeInner_repeat2 = 33,
  aux_sym_typeInner_repeat3 = 34,
  aux_sym_funcHead_repeat1 = 35,
  aux_sym_funcHead_repeat2 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_async] = "async",
  [anon_sym_const] = "const",
  [anon_sym_export] = "export",
  [anon_sym_builtin] = "builtin",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [sym_klass] = "klass",
  [sym_source_file] = "source_file",
  [sym__typeArgs] = "_typeArgs",
  [sym_typeExpr] = "typeExpr",
  [sym_typeName] = "typeName",
  [sym_typeDecl] = "typeDecl",
  [sym_typeInner] = "typeInner",
  [sym_typeAnnotated] = "typeAnnotated",
  [sym_funcHead] = "funcHead",
  [sym_func] = "func",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__typeArgs_repeat1] = "_typeArgs_repeat1",
  [aux_sym_typeName_repeat1] = "typeName_repeat1",
  [aux_sym_typeInner_repeat1] = "typeInner_repeat1",
  [aux_sym_typeInner_repeat2] = "typeInner_repeat2",
  [aux_sym_typeInner_repeat3] = "typeInner_repeat3",
  [aux_sym_funcHead_repeat1] = "funcHead_repeat1",
  [aux_sym_funcHead_repeat2] = "funcHead_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_async] = anon_sym_async,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_builtin] = anon_sym_builtin,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_klass] = sym_klass,
  [sym_source_file] = sym_source_file,
  [sym__typeArgs] = sym__typeArgs,
  [sym_typeExpr] = sym_typeExpr,
  [sym_typeName] = sym_typeName,
  [sym_typeDecl] = sym_typeDecl,
  [sym_typeInner] = sym_typeInner,
  [sym_typeAnnotated] = sym_typeAnnotated,
  [sym_funcHead] = sym_funcHead,
  [sym_func] = sym_func,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__typeArgs_repeat1] = aux_sym__typeArgs_repeat1,
  [aux_sym_typeName_repeat1] = aux_sym_typeName_repeat1,
  [aux_sym_typeInner_repeat1] = aux_sym_typeInner_repeat1,
  [aux_sym_typeInner_repeat2] = aux_sym_typeInner_repeat2,
  [aux_sym_typeInner_repeat3] = aux_sym_typeInner_repeat3,
  [aux_sym_funcHead_repeat1] = aux_sym_funcHead_repeat1,
  [aux_sym_funcHead_repeat2] = aux_sym_funcHead_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_async] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_builtin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_klass] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__typeArgs] = {
    .visible = false,
    .named = true,
  },
  [sym_typeExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_typeName] = {
    .visible = true,
    .named = true,
  },
  [sym_typeDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_typeInner] = {
    .visible = true,
    .named = true,
  },
  [sym_typeAnnotated] = {
    .visible = true,
    .named = true,
  },
  [sym_funcHead] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__typeArgs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeName_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeInner_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeInner_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typeInner_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_funcHead_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_args = 1,
  field_methods = 2,
  field_name = 3,
  field_return = 4,
  field_type = 5,
  field_typeAlias = 6,
  field_typeInner = 7,
  field_typeInnerProperties = 8,
  field_typeInnerVariants = 9,
  field_typeName = 10,
  field_variant = 11,
  field_variantName = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_methods] = "methods",
  [field_name] = "name",
  [field_return] = "return",
  [field_type] = "type",
  [field_typeAlias] = "typeAlias",
  [field_typeInner] = "typeInner",
  [field_typeInnerProperties] = "typeInnerProperties",
  [field_typeInnerVariants] = "typeInnerVariants",
  [field_typeName] = "typeName",
  [field_variant] = "variant",
  [field_variantName] = "variantName",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 4},
  [10] = {.index = 18, .length = 1},
  [11] = {.index = 19, .length = 2},
  [12] = {.index = 21, .length = 1},
  [13] = {.index = 22, .length = 2},
  [14] = {.index = 24, .length = 4},
  [15] = {.index = 28, .length = 2},
  [16] = {.index = 30, .length = 4},
  [17] = {.index = 34, .length = 3},
  [18] = {.index = 37, .length = 3},
  [19] = {.index = 40, .length = 2},
  [20] = {.index = 42, .length = 5},
  [21] = {.index = 47, .length = 4},
  [22] = {.index = 51, .length = 3},
  [23] = {.index = 54, .length = 3},
  [24] = {.index = 57, .length = 5},
  [25] = {.index = 62, .length = 4},
  [26] = {.index = 66, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_typeName, 1},
  [1] =
    {field_typeInner, 2},
    {field_typeName, 1},
  [3] =
    {field_typeAlias, 2},
    {field_typeAlias, 3},
    {field_typeName, 1},
  [6] =
    {field_variantName, 0},
  [7] =
    {field_name, 1},
  [8] =
    {field_variant, 1},
    {field_variantName, 0},
  [10] =
    {field_typeInnerProperties, 1},
  [11] =
    {field_typeInnerVariants, 1},
    {field_variant, 1, .inherited = true},
    {field_variantName, 1, .inherited = true},
  [14] =
    {field_variant, 0, .inherited = true},
    {field_variant, 1, .inherited = true},
    {field_variantName, 0, .inherited = true},
    {field_variantName, 1, .inherited = true},
  [18] =
    {field_methods, 1},
  [19] =
    {field_args, 3},
    {field_name, 1},
  [21] =
    {field_name, 2},
  [22] =
    {field_name, 0},
    {field_type, 2},
  [24] =
    {field_typeInnerProperties, 1},
    {field_typeInnerVariants, 2},
    {field_variant, 2, .inherited = true},
    {field_variantName, 2, .inherited = true},
  [28] =
    {field_methods, 2},
    {field_typeInnerProperties, 1},
  [30] =
    {field_methods, 2},
    {field_typeInnerVariants, 1},
    {field_variant, 1, .inherited = true},
    {field_variantName, 1, .inherited = true},
  [34] =
    {field_name, 1},
    {field_return, 4},
    {field_return, 5},
  [37] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
  [40] =
    {field_args, 4},
    {field_name, 2},
  [42] =
    {field_methods, 3},
    {field_typeInnerProperties, 1},
    {field_typeInnerVariants, 2},
    {field_variant, 2, .inherited = true},
    {field_variantName, 2, .inherited = true},
  [47] =
    {field_args, 3},
    {field_name, 1},
    {field_return, 5},
    {field_return, 6},
  [51] =
    {field_name, 2},
    {field_return, 5},
    {field_return, 6},
  [54] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
  [57] =
    {field_args, 3},
    {field_args, 4},
    {field_name, 1},
    {field_return, 6},
    {field_return, 7},
  [62] =
    {field_args, 4},
    {field_name, 2},
    {field_return, 6},
    {field_return, 7},
  [66] =
    {field_args, 4},
    {field_args, 5},
    {field_name, 2},
    {field_return, 7},
    {field_return, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '#') SKIP(2)
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == ']') ADVANCE(6);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') SKIP(0)
      if (lookahead != 0) SKIP(2)
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '#') SKIP(1)
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'b') ADVANCE(3);
      if (lookahead == 'c') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0)
      if (lookahead != 0) SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'x') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'y') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_async);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_klass);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_builtin);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_async] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_builtin] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_klass] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(70),
    [sym_typeDecl] = STATE(10),
    [sym_funcHead] = STATE(75),
    [sym_func] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_funcHead_repeat1] = STATE(37),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(5),
    [anon_sym_async] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_export] = ACTIONS(7),
    [anon_sym_builtin] = ACTIONS(7),
    [anon_sym_func] = ACTIONS(9),
    [sym_klass] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(17), 1,
      anon_sym_DOT,
    STATE(3), 1,
      aux_sym_typeName_repeat1,
    ACTIONS(13), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(15), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [26] = 4,
    ACTIONS(23), 1,
      anon_sym_DOT,
    STATE(3), 1,
      aux_sym_typeName_repeat1,
    ACTIONS(19), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(21), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [52] = 4,
    ACTIONS(17), 1,
      anon_sym_DOT,
    STATE(2), 1,
      aux_sym_typeName_repeat1,
    ACTIONS(26), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(28), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [78] = 2,
    ACTIONS(19), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(21), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [99] = 3,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(30), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(32), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [121] = 2,
    ACTIONS(36), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(38), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [140] = 9,
    ACTIONS(40), 1,
      sym_ident,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      anon_sym_func,
    STATE(13), 1,
      aux_sym_typeInner_repeat2,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(19), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    STATE(32), 2,
      sym_typeAnnotated,
      aux_sym_typeInner_repeat1,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [173] = 9,
    ACTIONS(40), 1,
      sym_ident,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_typeInner_repeat2,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(8), 2,
      sym_typeAnnotated,
      aux_sym_typeInner_repeat1,
    STATE(27), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [206] = 8,
    ACTIONS(5), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_klass,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(11), 3,
      sym_typeDecl,
      sym_func,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [236] = 8,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      anon_sym_type,
    ACTIONS(62), 1,
      anon_sym_func,
    ACTIONS(65), 1,
      sym_klass,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(11), 3,
      sym_typeDecl,
      sym_func,
      aux_sym_source_file_repeat1,
    ACTIONS(59), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [266] = 8,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(68), 1,
      sym_ident,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_typeInner_repeat2,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(16), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [295] = 8,
    ACTIONS(46), 1,
      anon_sym_func,
    ACTIONS(68), 1,
      sym_ident,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_typeInner_repeat2,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(15), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(44), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [324] = 4,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_typeInner,
    ACTIONS(74), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [344] = 6,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(21), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(7), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [367] = 6,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(21), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(7), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [390] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(86), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [405] = 2,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(90), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [420] = 6,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(21), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(7), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [443] = 2,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(96), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [458] = 6,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 1,
      anon_sym_func,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(21), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(100), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [481] = 2,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(108), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [496] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(112), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [511] = 5,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(36), 1,
      sym_typeInner,
    ACTIONS(114), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [532] = 2,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(122), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [547] = 2,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(126), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [562] = 6,
    ACTIONS(9), 1,
      anon_sym_func,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_funcHead_repeat1,
    STATE(75), 1,
      sym_funcHead,
    STATE(21), 2,
      sym_func,
      aux_sym_typeInner_repeat3,
    ACTIONS(7), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [585] = 2,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(132), 8,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
      sym_ident,
  [600] = 4,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      sym_typeInner,
    ACTIONS(114), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [618] = 2,
    ACTIONS(136), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(134), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [632] = 1,
    ACTIONS(138), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_RBRACE,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [644] = 4,
    ACTIONS(140), 1,
      sym_ident,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_typeAnnotated,
      aux_sym_typeInner_repeat1,
    ACTIONS(145), 5,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [662] = 1,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [673] = 1,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_klass,
  [684] = 4,
    ACTIONS(151), 1,
      sym_ident,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_typeInner_repeat2,
    ACTIONS(156), 5,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
  [701] = 2,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(158), 6,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
      anon_sym_func,
      sym_ident,
  [713] = 3,
    ACTIONS(164), 1,
      anon_sym_func,
    STATE(38), 1,
      aux_sym_funcHead_repeat1,
    ACTIONS(162), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [726] = 3,
    ACTIONS(169), 1,
      anon_sym_func,
    STATE(38), 1,
      aux_sym_funcHead_repeat1,
    ACTIONS(166), 4,
      anon_sym_async,
      anon_sym_const,
      anon_sym_export,
      anon_sym_builtin,
  [739] = 4,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(40), 1,
      sym_typeExpr,
    STATE(69), 1,
      sym__typeArgs,
  [752] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym__typeArgs_repeat1,
  [762] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_funcHead_repeat2,
  [772] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(30), 1,
      sym_typeExpr,
  [782] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(84), 1,
      sym_typeExpr,
  [792] = 3,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym__typeArgs_repeat1,
  [802] = 3,
    ACTIONS(186), 1,
      sym_ident,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym_typeAnnotated,
  [812] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(33), 1,
      sym_typeExpr,
  [822] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(80), 1,
      sym_typeExpr,
  [832] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(82), 1,
      sym_typeExpr,
  [842] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(81), 1,
      sym_typeExpr,
  [852] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_funcHead_repeat2,
  [862] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym__typeArgs_repeat1,
  [872] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_funcHead_repeat2,
  [882] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(62), 1,
      sym_typeExpr,
  [892] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_funcHead_repeat2,
  [902] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(76), 1,
      sym_typeExpr,
  [912] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_funcHead_repeat2,
  [922] = 3,
    ACTIONS(186), 1,
      sym_ident,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_typeAnnotated,
  [932] = 3,
    ACTIONS(171), 1,
      sym_ident,
    STATE(6), 1,
      sym_typeName,
    STATE(74), 1,
      sym_typeExpr,
  [942] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [947] = 2,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    ACTIONS(207), 1,
      anon_sym_DASH_GT,
  [954] = 2,
    ACTIONS(186), 1,
      sym_ident,
    STATE(59), 1,
      sym_typeAnnotated,
  [961] = 1,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [966] = 2,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    ACTIONS(211), 1,
      anon_sym_DASH_GT,
  [973] = 2,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_DASH_GT,
  [980] = 2,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    ACTIONS(219), 1,
      anon_sym_DASH_GT,
  [987] = 2,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      anon_sym_DASH_GT,
  [994] = 2,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_DASH_GT,
  [1001] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
  [1005] = 1,
    ACTIONS(231), 1,
      anon_sym_RBRACK,
  [1009] = 1,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [1013] = 1,
    ACTIONS(235), 1,
      sym_ident,
  [1017] = 1,
    ACTIONS(118), 1,
      anon_sym_COLON,
  [1021] = 1,
    ACTIONS(237), 1,
      sym_ident,
  [1025] = 1,
    ACTIONS(239), 1,
      anon_sym_LBRACE,
  [1029] = 1,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [1033] = 1,
    ACTIONS(243), 1,
      anon_sym_LBRACE,
  [1037] = 1,
    ACTIONS(245), 1,
      anon_sym_LPAREN,
  [1041] = 1,
    ACTIONS(247), 1,
      sym_ident,
  [1045] = 1,
    ACTIONS(249), 1,
      sym_ident,
  [1049] = 1,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
  [1053] = 1,
    ACTIONS(253), 1,
      anon_sym_LBRACE,
  [1057] = 1,
    ACTIONS(255), 1,
      anon_sym_LBRACE,
  [1061] = 1,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
  [1065] = 1,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 99,
  [SMALL_STATE(7)] = 121,
  [SMALL_STATE(8)] = 140,
  [SMALL_STATE(9)] = 173,
  [SMALL_STATE(10)] = 206,
  [SMALL_STATE(11)] = 236,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 295,
  [SMALL_STATE(14)] = 324,
  [SMALL_STATE(15)] = 344,
  [SMALL_STATE(16)] = 367,
  [SMALL_STATE(17)] = 390,
  [SMALL_STATE(18)] = 405,
  [SMALL_STATE(19)] = 420,
  [SMALL_STATE(20)] = 443,
  [SMALL_STATE(21)] = 458,
  [SMALL_STATE(22)] = 481,
  [SMALL_STATE(23)] = 496,
  [SMALL_STATE(24)] = 511,
  [SMALL_STATE(25)] = 532,
  [SMALL_STATE(26)] = 547,
  [SMALL_STATE(27)] = 562,
  [SMALL_STATE(28)] = 585,
  [SMALL_STATE(29)] = 600,
  [SMALL_STATE(30)] = 618,
  [SMALL_STATE(31)] = 632,
  [SMALL_STATE(32)] = 644,
  [SMALL_STATE(33)] = 662,
  [SMALL_STATE(34)] = 673,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 701,
  [SMALL_STATE(37)] = 713,
  [SMALL_STATE(38)] = 726,
  [SMALL_STATE(39)] = 739,
  [SMALL_STATE(40)] = 752,
  [SMALL_STATE(41)] = 762,
  [SMALL_STATE(42)] = 772,
  [SMALL_STATE(43)] = 782,
  [SMALL_STATE(44)] = 792,
  [SMALL_STATE(45)] = 802,
  [SMALL_STATE(46)] = 812,
  [SMALL_STATE(47)] = 822,
  [SMALL_STATE(48)] = 832,
  [SMALL_STATE(49)] = 842,
  [SMALL_STATE(50)] = 852,
  [SMALL_STATE(51)] = 862,
  [SMALL_STATE(52)] = 872,
  [SMALL_STATE(53)] = 882,
  [SMALL_STATE(54)] = 892,
  [SMALL_STATE(55)] = 902,
  [SMALL_STATE(56)] = 912,
  [SMALL_STATE(57)] = 922,
  [SMALL_STATE(58)] = 932,
  [SMALL_STATE(59)] = 942,
  [SMALL_STATE(60)] = 947,
  [SMALL_STATE(61)] = 954,
  [SMALL_STATE(62)] = 961,
  [SMALL_STATE(63)] = 966,
  [SMALL_STATE(64)] = 973,
  [SMALL_STATE(65)] = 980,
  [SMALL_STATE(66)] = 987,
  [SMALL_STATE(67)] = 994,
  [SMALL_STATE(68)] = 1001,
  [SMALL_STATE(69)] = 1005,
  [SMALL_STATE(70)] = 1009,
  [SMALL_STATE(71)] = 1013,
  [SMALL_STATE(72)] = 1017,
  [SMALL_STATE(73)] = 1021,
  [SMALL_STATE(74)] = 1025,
  [SMALL_STATE(75)] = 1029,
  [SMALL_STATE(76)] = 1033,
  [SMALL_STATE(77)] = 1037,
  [SMALL_STATE(78)] = 1041,
  [SMALL_STATE(79)] = 1045,
  [SMALL_STATE(80)] = 1049,
  [SMALL_STATE(81)] = 1053,
  [SMALL_STATE(82)] = 1057,
  [SMALL_STATE(83)] = 1061,
  [SMALL_STATE(84)] = 1065,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 2),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeName_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeName_repeat1, 2), SHIFT_REPEAT(79),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeName, 1),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeName, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 1),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeExpr, 4),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeExpr, 4),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(78),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 2, .production_id = 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 3, .production_id = 10),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 3, .production_id = 10),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 3, .production_id = 8),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 3, .production_id = 8),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 5, .production_id = 20),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 5, .production_id = 20),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat3, 2),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat3, 2), SHIFT_REPEAT(37),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat3, 2), SHIFT_REPEAT(73),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 4, .production_id = 14),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 4, .production_id = 14),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 2),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat2, 1, .production_id = 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat2, 1, .production_id = 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 4, .production_id = 15),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 4, .production_id = 15),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 4, .production_id = 16),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 4, .production_id = 16),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeInner, 3, .production_id = 7),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeInner, 3, .production_id = 7),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeAnnotated, 3, .production_id = 13),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 3),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat1, 2), SHIFT_REPEAT(72),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat1, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 4, .production_id = 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 3, .production_id = 2),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat2, 2, .production_id = 9), SHIFT_REPEAT(29),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat2, 2, .production_id = 9),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat2, 2, .production_id = 9),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_typeInner_repeat2, 2, .production_id = 6),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typeInner_repeat2, 2, .production_id = 6),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2), SHIFT_REPEAT(38),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat1, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2), SHIFT_REPEAT(53),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__typeArgs_repeat1, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeArgs, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2), SHIFT_REPEAT(61),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_funcHead_repeat2, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 19),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 23),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 11),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 18),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 5, .production_id = 12),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 4, .production_id = 5),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [233] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 21),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 7, .production_id = 22),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 6, .production_id = 17),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 24),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 8, .production_id = 25),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcHead, 9, .production_id = 26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ridotto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
