[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
paste = "1.0.15"
proc-macro2 = "1.0.101"
quote = "1.0.40"
stringcase = "0.4.0"
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
